In [1]:
import numpy as np
import cv2 

In [2]:
#loading the image
img=cv2.imread('faces.jpg')
cv2.imshow('Test image',img)
cv2.waitKey(0)==ord('q')
cv2.destroyAllWindows()

In [3]:
#well load the classifier
face_cascade=cv2.CascadeClassifier('./model/haarcascade_frontalface_default.xml')

In [6]:
#the first step is to convert the image to grayscale
gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#second step is to apply the cascade classifier to the image
#this will return objects and number of detections
box,number_of_detections=face_cascade.detectMultiScale2(gray_image,)

In [7]:
box

array([[321,  84, 385, 385],
       [ 88,  75, 316, 316],
       [697, 107, 248, 248],
       [894, 573,  52,  52]])

In [8]:
number_of_detections

array([35, 10, 37,  4])

we didint set the minNumber of neighbours argument in the face_cascade, lets set it to 8

In [9]:
#the first step is to convert the image to grayscale
gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#second step is to apply the cascade classifier to the image
#this will return objects and number of detections
box,number_of_detections=face_cascade.detectMultiScale2(gray_image,minNeighbors=8)

In [10]:
box

array([[321,  84, 385, 385],
       [ 88,  75, 316, 316],
       [697, 107, 248, 248]])

In [11]:
number_of_detections

array([35, 10, 37])

Expalantion: the box represents the bounding boxes, they are 3 in number, the first part represents the x ,second part represents y, 3rd is width and the 4th is height, more precisely this array represnts coordinates of the bounding box over the face detected.